// comm-canoe database schema — collapsed final state as of the last applied
// migration (supabase/migrations/20250701002400_tenant_reside_app_url.sql).
//
// Generated by reading supabase/migrations/*.sql in filename order and
// applying every CREATE/ALTER/DROP in sequence, cross-checked against
// packages/database/src/types.ts. This file represents ONLY the end state —
// renamed/altered/dropped objects from migration history do not appear (see
// notes.md for the full list of what was collapsed away, and for every
// discrepancy found between the migrations and types.ts).
//
// NOT included here (see notes.md for why):
//   - better-auth tables ("user", "session", "account", "verification") —
//     created out-of-band by `better-auth migrate`. They live alongside these
//     tables in this database's `public` schema, and are excluded from
//     drizzle-kit's diff by tablesFilter in drizzle.config.ts.
//   - RLS policies — inert under Better Auth (they all read auth.uid(), which
//     Supabase Auth no longer supplies) and bypassed regardless by the
//     migration role's BYPASSRLS. What replaces them is split: isolation
//     BETWEEN products comes from the bootstrap SQL, which puts comm-canoe and
//     reside in separate logical databases on one cluster with neither role
//     holding CONNECT on the other's; isolation BETWEEN TENANTS within
//     comm-canoe is application-layer only, with no backstop underneath it,
//     and src/services/tenant-isolation.test.ts is what the cutover traded the
//     policies for.
//   - get_user_tenant_ids() and the RLS-auto-enable event trigger — purely
//     RLS-support plumbing with no application code path (see notes.md).
//
// Schema placement: everything below lives in `public`, same as under
// Supabase. Isolation from reside comes from being a separate logical
// database on the shared cluster rather than a separate schema in a shared
// one — PlanetScale's own pattern for multiple apps on one cluster, and the
// stronger of the two: reside's role has no CONNECT privilege here at all,
// rather than merely no GRANT on the tables. The tradeoff is that a
// cross-product join is impossible rather than just ungranted, which suits
// two products deliberately coupled only by reside's client uid.
//
// Naming convention: TS fields are camelCase; every column is given an
// EXPLICIT snake_case db name rather than relying on drizzle's
// `casing: "snake_case"` option. Both consumers do set that option today
// (packages/database/src/db.ts for the runtime client, drizzle.config.ts for
// drizzle-kit), but they set it independently, and if the two ever disagree
// the generated DDL and the ORM's queries silently describe different
// columns. Writing every name out makes the option a safety net rather than
// the only thing holding it together — see notes.md, "Naming convention /
// casing gap".

import { sql } from "drizzle-orm";
import {
  pgTable,
  pgEnum,
  uuid,
  text,
  timestamp,
  boolean,
  integer,
  jsonb,
  vector,
  index,
  uniqueIndex,
  unique,
  check,
  primaryKey,
  type AnyPgColumn,
} from "drizzle-orm/pg-core";

/**
 * Everything below lives in `public`, inside comm-canoe's own logical database
 * on the shared PlanetScale cluster (see
 * packages/database/sql/00-bootstrap-database-and-role.sql). reside owns a
 * sibling database, not a sibling schema, so a cross-product FK is not merely
 * absent by convention — Postgres cannot express one across databases.
 */

// ---------------------------------------------------------------------------
// Enums
//
// Values reflect the final state after every `ALTER TYPE ... ADD VALUE` was
// applied. One type was renamed in-place (call_transfer_outcome ->
// live_transfer_outcome); the Postgres type — and therefore this enum —
// carries only the final name. All enums live in `public`, like everything
// else here.
// ---------------------------------------------------------------------------

/** 20250620160000 (created) + 20250701001200 (added 'merged') */
export const conversationStatusEnum = pgEnum("conversation_status", [
  "open",
  "pending",
  "resolved",
  "merged",
]);

/** 20250620160000 (created) + 20250621140000 (added 'web_chat') */
export const messageChannelEnum = pgEnum("message_channel", [
  "voice",
  "sms",
  "email",
  "web_chat",
]);

export const messageDirectionEnum = pgEnum("message_direction", [
  "inbound",
  "outbound",
]);

/** 20250620160000 (created) + 20250625090000 (added 'system') */
export const senderTypeEnum = pgEnum("sender_type", [
  "external",
  "internal_user",
  "ai_agent",
  "system",
]);

export const mergeMatchedOnEnum = pgEnum("merge_matched_on", [
  "phone",
  "email",
]);

export const mergeActorEnum = pgEnum("merge_actor", ["system", "user"]);

/**
 * 20250620160000: created as `call_transfer_outcome` ('answered',
 * 'no_answer', 'declined').
 * 20250621140000: `ALTER TYPE call_transfer_outcome RENAME TO
 * live_transfer_outcome`, then `ADD VALUE 'pending'`.
 * The underlying pg_type is live_transfer_outcome — that's the only name
 * that exists in the final DB, so that's what's emitted here.
 */
export const liveTransferOutcomeEnum = pgEnum("live_transfer_outcome", [
  "answered",
  "no_answer",
  "declined",
  "pending",
]);

export const tenantRoleEnum = pgEnum("tenant_role", ["admin", "member"]);

export const teamRoleEnum = pgEnum("team_role", ["lead", "member"]);

/** 20250621130000 */
export const platformRoleEnum = pgEnum("platform_role", [
  "user",
  "super_admin",
]);

/** 20250621140000 */
export const liveTransferChannelEnum = pgEnum("live_transfer_channel", [
  "voice",
  "web_chat",
]);

/**
 * 20250625100000 (created) + 20250701000800 (added 'sending', 'canceled')
 */
export const messageDeliveryStatusEnum = pgEnum("message_delivery_status", [
  "queued",
  "sent",
  "delivered",
  "failed",
  "undelivered",
  "sending",
  "canceled",
]);

/** 20250701000500 */
export const messageVisibilityEnum = pgEnum("message_visibility", [
  "internal",
  "external",
]);

/** 20250701000700 */
export const conversationPriorityEnum = pgEnum("conversation_priority", [
  "low",
  "normal",
  "high",
  "urgent",
]);

// ---------------------------------------------------------------------------
// Tenants
// ---------------------------------------------------------------------------

export const tenants = pgTable(
  "tenants",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    name: text("name").notNull(),
    twilioNumber: text("twilio_number").notNull(),
    inboundEmailAddress: text("inbound_email_address").notNull(),
    /**
     * 20250621140000: added nullable, backfilled with gen_random_uuid()::text,
     * then SET NOT NULL. No DB-level DEFAULT was ever attached, so every
     * insert must supply a key — createTenant does, via generateWidgetKey().
     * types.ts marked this optional on insert until notes.md discrepancy #1
     * was fixed; do not add a DEFAULT here to make it optional again.
     */
    chatWidgetKey: text("chat_widget_key").notNull(),
    /** 20250625090000 */
    provisioningSource: text("provisioning_source")
      .notNull()
      .default("manual"),
    /**
     * 20250701002000: reside's own client identifier (may be a non-UUID
     * slug, e.g. "cardiff"). Decoupled from `id` — every tenant_id FK in
     * this schema still points at `id`, never at this column. Backfilled
     * from `id::text` for pre-existing rows; no DB default going forward.
     */
    resideClientUid: text("reside_client_uid").notNull(),
    /** 20250701002400 — null falls back to the RESIDE_APP_URL env var */
    resideAppUrl: text("reside_app_url"),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    unique("tenants_twilio_number_unique").on(t.twilioNumber),
    unique("tenants_inbound_email_unique").on(t.inboundEmailAddress),
    unique("tenants_chat_widget_key_unique").on(t.chatWidgetKey),
    unique("tenants_reside_client_uid_unique").on(t.resideClientUid),
    check(
      "tenants_provisioning_source_check",
      sql`${t.provisioningSource} in ('manual', 'reside')`,
    ),
    // These duplicate the implicit indexes backing the UNIQUE constraints
    // above (btree on the same single column) — that redundancy is in the
    // original migrations verbatim (explicit CREATE INDEX alongside a
    // CONSTRAINT ... UNIQUE on the same column), not an artifact of this
    // port. See notes.md.
    index("tenants_twilio_number_idx").on(t.twilioNumber),
    index("tenants_inbound_email_idx").on(t.inboundEmailAddress),
    index("tenants_reside_client_uid_idx").on(t.resideClientUid),
  ],
);

// ---------------------------------------------------------------------------
// Tenant settings
// ---------------------------------------------------------------------------

export const tenantSettings = pgTable("tenant_settings", {
  tenantId: uuid("tenant_id")
    .primaryKey()
    .references(() => tenants.id, { onDelete: "cascade" }),
  greetingMessage: text("greeting_message"),
  businessHours: jsonb("business_hours").default({}),
  faqSnippets: jsonb("faq_snippets").default([]),
  autoReplySms: boolean("auto_reply_sms").notNull().default(false),
  /** 20250701000200 */
  bounceThreshold: integer("bounce_threshold").notNull().default(3),
  /** 20250701000500 */
  externalSendDelaySeconds: integer("external_send_delay_seconds")
    .notNull()
    .default(60),
  /** 20250701000700 */
  defaultResponseWindowMinutes: integer("default_response_window_minutes")
    .notNull()
    .default(60),
  /** 20250701001400 */
  conversationStalenessMinutes: integer("conversation_staleness_minutes")
    .notNull()
    .default(1440),
  /** 20250701001500 */
  maxKnowledgeDocuments: integer("max_knowledge_documents")
    .notNull()
    .default(50),
  maxKnowledgeChunks: integer("max_knowledge_chunks").notNull().default(5000),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
});

// ---------------------------------------------------------------------------
// Users (app-domain profile; identity/sessions owned by Better Auth)
// ---------------------------------------------------------------------------

export const users = pgTable(
  "users",
  {
    /**
     * 20250620160000: originally `REFERENCES auth.users (id) ON DELETE
     * CASCADE`. 20250621120000 ("better_auth_decouple"): that FK constraint
     * was dropped (`DROP CONSTRAINT IF EXISTS users_id_fkey`) because
     * Supabase Auth was replaced by Better Auth. There is NO enforced FK to
     * a "user" table in the final schema — id is expected to match Better
     * Auth's `user.id`, but only by convention (per
     * `COMMENT ON TABLE public.users IS 'App-domain profile; id matches
     * Better Auth user.id'`), unchecked by the database.
     */
    id: uuid("id").primaryKey(),
    name: text("name"),
    email: text("email").notNull(),
    phoneNumber: text("phone_number"),
    availableForCalls: boolean("available_for_calls")
      .notNull()
      .default(false),
    /** 20250621130000 */
    platformRole: platformRoleEnum("platform_role").notNull().default("user"),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    // Not unique in the original — just a lookup index. Do not tighten to
    // unique() when porting; nothing in the migration history enforces it.
    index("users_email_idx").on(t.email),
  ],
);

// ---------------------------------------------------------------------------
// User <-> tenant membership
// ---------------------------------------------------------------------------

export const userTenantMemberships = pgTable(
  "user_tenant_memberships",
  {
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    tenantId: uuid("tenant_id")
      .notNull()
      .references(() => tenants.id, { onDelete: "cascade" }),
    role: tenantRoleEnum("role").notNull().default("member"),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    primaryKey({ columns: [t.userId, t.tenantId] }),
    index("user_tenant_memberships_tenant_idx").on(t.tenantId),
  ],
);

// ---------------------------------------------------------------------------
// Teams
// ---------------------------------------------------------------------------

export const teams = pgTable(
  "teams",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    tenantId: uuid("tenant_id")
      .notNull()
      .references(() => tenants.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    unique("teams_tenant_name_unique").on(t.tenantId, t.name),
    index("teams_tenant_idx").on(t.tenantId),
  ],
);

// ---------------------------------------------------------------------------
// Team membership
// ---------------------------------------------------------------------------

export const teamMemberships = pgTable(
  "team_memberships",
  {
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    teamId: uuid("team_id")
      .notNull()
      .references(() => teams.id, { onDelete: "cascade" }),
    role: teamRoleEnum("role").notNull().default("member"),
    isOnCall: boolean("is_on_call").notNull().default(false),
  },
  (t) => [
    primaryKey({ columns: [t.userId, t.teamId] }),
    index("team_memberships_team_idx").on(t.teamId),
  ],
);

// ---------------------------------------------------------------------------
// Identities (customers)
// ---------------------------------------------------------------------------

export const identities = pgTable(
  "identities",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    tenantId: uuid("tenant_id")
      .notNull()
      .references(() => tenants.id, { onDelete: "cascade" }),
    phone: text("phone"),
    email: text("email"),
    name: text("name"),
    /** 20250621140000 — enables anonymous web-chat identities */
    isAnonymous: boolean("is_anonymous").notNull().default(false),
    mergedIntoId: uuid("merged_into_id").references(
      (): AnyPgColumn => identities.id,
      { onDelete: "set null" },
    ),
    /** 20250625090000 — cross-system link to a reside resident record */
    resideResidentId: uuid("reside_resident_id"),
    /** 20250701000200 (bounce-threshold tracking) */
    emailConsecutiveFailures: integer("email_consecutive_failures")
      .notNull()
      .default(0),
    phoneConsecutiveFailures: integer("phone_consecutive_failures")
      .notNull()
      .default(0),
    emailFlaggedAt: timestamp("email_flagged_at", { withTimezone: true }),
    phoneFlaggedAt: timestamp("phone_flagged_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    // Final version of this CHECK (20250621140000 replaced the original
    // "phone or email" check to also allow anonymous web-chat identities).
    check(
      "identities_contact_required",
      sql`${t.phone} is not null or ${t.email} is not null or ${t.isAnonymous} = true`,
    ),
    check(
      "identities_no_self_merge",
      sql`${t.mergedIntoId} is distinct from ${t.id}`,
    ),
    index("identities_tenant_idx").on(t.tenantId),
    uniqueIndex("identities_tenant_phone_unique")
      .on(t.tenantId, t.phone)
      .where(sql`${t.phone} is not null`),
    uniqueIndex("identities_tenant_email_unique")
      .on(t.tenantId, t.email)
      .where(sql`${t.email} is not null`),
    index("identities_merged_into_idx")
      .on(t.mergedIntoId)
      .where(sql`${t.mergedIntoId} is not null`),
    /** 20250625090000 */
    uniqueIndex("identities_tenant_reside_resident_unique")
      .on(t.tenantId, t.resideResidentId)
      .where(sql`${t.resideResidentId} is not null`),
  ],
);

// ---------------------------------------------------------------------------
// Identity merge audit log
// ---------------------------------------------------------------------------

export const identityMergeLogs = pgTable(
  "identity_merge_logs",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    tenantId: uuid("tenant_id")
      .notNull()
      .references(() => tenants.id, { onDelete: "cascade" }),
    identityAId: uuid("identity_a_id")
      .notNull()
      .references(() => identities.id, { onDelete: "cascade" }),
    identityBId: uuid("identity_b_id")
      .notNull()
      .references(() => identities.id, { onDelete: "cascade" }),
    matchedOn: mergeMatchedOnEnum("matched_on").notNull(),
    mergedAt: timestamp("merged_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    mergedBy: mergeActorEnum("merged_by").notNull().default("system"),
    mergedByUserId: uuid("merged_by_user_id").references(() => users.id, {
      onDelete: "set null",
    }),
    unmergedAt: timestamp("unmerged_at", { withTimezone: true }),
  },
  (t) => [index("identity_merge_logs_tenant_idx").on(t.tenantId)],
);

// ---------------------------------------------------------------------------
// Identity conversion audit log (anonymous web-chat identity -> real contact)
// ---------------------------------------------------------------------------

/** 20250621140000 */
export const identityConversionLogs = pgTable(
  "identity_conversion_logs",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    tenantId: uuid("tenant_id")
      .notNull()
      .references(() => tenants.id, { onDelete: "cascade" }),
    identityId: uuid("identity_id")
      .notNull()
      .references(() => identities.id, { onDelete: "cascade" }),
    convertedAt: timestamp("converted_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    convertedBy: mergeActorEnum("converted_by").notNull().default("system"),
    convertedByUserId: uuid("converted_by_user_id").references(
      () => users.id,
      { onDelete: "set null" },
    ),
    capturedName: text("captured_name"),
    capturedEmail: text("captured_email"),
    capturedPhone: text("captured_phone"),
  },
  (t) => [
    index("identity_conversion_logs_tenant_idx").on(t.tenantId),
    index("identity_conversion_logs_identity_idx").on(t.identityId),
  ],
);

// ---------------------------------------------------------------------------
// Conversations
// ---------------------------------------------------------------------------

export const conversations = pgTable(
  "conversations",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    tenantId: uuid("tenant_id")
      .notNull()
      .references(() => tenants.id, { onDelete: "cascade" }),
    identityId: uuid("identity_id")
      .notNull()
      .references(() => identities.id, { onDelete: "cascade" }),
    status: conversationStatusEnum("status").notNull().default("open"),
    assignedTeamId: uuid("assigned_team_id").references(() => teams.id, {
      onDelete: "set null",
    }),
    assignedUserId: uuid("assigned_user_id").references(() => users.id, {
      onDelete: "set null",
    }),
    summary: text("summary"),
    /** 20250701000700 */
    priority: conversationPriorityEnum("priority").notNull().default("normal"),
    responseDueAt: timestamp("response_due_at", { withTimezone: true }),
    /** 20250701001000 — set/cleared by messages_update_conversation_response_due_at trigger */
    responseOverdueNotifiedAt: timestamp("response_overdue_notified_at", {
      withTimezone: true,
    }),
    /** 20250701001200 */
    mergedIntoId: uuid("merged_into_id").references(
      (): AnyPgColumn => conversations.id,
      { onDelete: "set null" },
    ),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    lastMessageAt: timestamp("last_message_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    index("conversations_tenant_last_message_idx").on(
      t.tenantId,
      t.lastMessageAt.desc(),
    ),
    index("conversations_identity_idx").on(t.identityId),
    // NOTE: `conversations_one_open_per_identity` — a UNIQUE index on
    // (tenant_id, identity_id) WHERE status = 'open' — existed from
    // 20250620160000 through 20250701001300, where it was dropped
    // outright (Phase 8, conversation splitting requires 2+ simultaneously
    // open conversations per identity). Per the collapse-history
    // requirement, it is NOT emitted here.
    /** 20250701000700 */
    index("conversations_response_due_idx")
      .on(t.responseDueAt)
      .where(sql`${t.responseDueAt} is not null`),
    /**
     * 20250701001400 — replaces the query-serving role of the dropped
     * unique index above, minus the uniqueness constraint (multi-open is
     * now a supported state).
     */
    index("conversations_tenant_identity_open_idx")
      .on(t.tenantId, t.identityId)
      .where(sql`${t.status} = 'open'`),
  ],
);

// ---------------------------------------------------------------------------
// Messages
// ---------------------------------------------------------------------------

export const messages = pgTable(
  "messages",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    tenantId: uuid("tenant_id")
      .notNull()
      .references(() => tenants.id, { onDelete: "cascade" }),
    conversationId: uuid("conversation_id")
      .notNull()
      .references(() => conversations.id, { onDelete: "cascade" }),
    channel: messageChannelEnum("channel").notNull(),
    direction: messageDirectionEnum("direction").notNull(),
    senderType: senderTypeEnum("sender_type").notNull(),
    // Polymorphic depending on senderType (user id, or null for
    // external/system) — deliberately has no FK, per the original schema.
    senderId: uuid("sender_id"),
    body: text("body").notNull().default(""),
    subject: text("subject"),
    audioUrl: text("audio_url"),
    transcript: text("transcript"),
    aiSummary: text("ai_summary"),
    /** 20250625100000 */
    providerMessageId: text("provider_message_id"),
    deliveryStatus: messageDeliveryStatusEnum("delivery_status"),
    deliveryError: text("delivery_error"),
    deliveryAttempts: integer("delivery_attempts").notNull().default(0),
    sentAt: timestamp("sent_at", { withTimezone: true }),
    deliveredAt: timestamp("delivered_at", { withTimezone: true }),
    /** 20250701000100 */
    openedAt: timestamp("opened_at", { withTimezone: true }),
    /** 20250701000500 */
    visibility: messageVisibilityEnum("visibility")
      .notNull()
      .default("internal"),
    scheduledSendAt: timestamp("scheduled_send_at", { withTimezone: true }),
    aiReviewStatus: text("ai_review_status"),
    /** 20250701001100 */
    aiReviewReasoning: text("ai_review_reasoning"),
    /** 20250701001400 */
    topicCheckStatus: text("topic_check_status"),
    /** 20250701002100 — only reside-originated sends carry a key */
    idempotencyKey: text("idempotency_key"),
    /**
     * 20250701001700 (created, check: pending/ready/failed) + 20250701002300
     * (constraint dropped and recreated to add 'transcribing' claim state).
     * Final constraint form below matches the recreated one verbatim.
     */
    transcriptionStatus: text("transcription_status"),
    transcriptionFailureReason: text("transcription_failure_reason"),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    check(
      "messages_ai_review_status_check",
      sql`${t.aiReviewStatus} in ('pending', 'approved', 'flagged')`,
    ),
    check(
      "messages_topic_check_status_check",
      sql`${t.topicCheckStatus} in ('pending', 'processing', 'reviewed')`,
    ),
    // Final form (20250701002300) — recreated with ANY(ARRAY[...]) syntax
    // rather than IN(...); semantically identical, kept literal here.
    check(
      "messages_transcription_status_check",
      sql`${t.transcriptionStatus} = any (array['pending', 'transcribing', 'ready', 'failed'])`,
    ),
    index("messages_conversation_created_idx").on(
      t.conversationId,
      t.createdAt,
    ),
    index("messages_tenant_idx").on(t.tenantId),
    index("messages_provider_message_id_idx")
      .on(t.providerMessageId)
      .where(sql`${t.providerMessageId} is not null`),
    /** 20250701002100 — scoped per tenant so two tenants can't collide on a key */
    uniqueIndex("messages_tenant_idempotency_key_unique")
      .on(t.tenantId, t.idempotencyKey)
      .where(sql`${t.idempotencyKey} is not null`),
  ],
);

// ---------------------------------------------------------------------------
// Live transfers (renamed from call_transfers in 20250621140000)
// ---------------------------------------------------------------------------

export const liveTransfers = pgTable(
  "live_transfers",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    tenantId: uuid("tenant_id")
      .notNull()
      .references(() => tenants.id, { onDelete: "cascade" }),
    conversationId: uuid("conversation_id")
      .notNull()
      .references(() => conversations.id, { onDelete: "cascade" }),
    messageId: uuid("message_id").references(() => messages.id, {
      onDelete: "set null",
    }),
    /**
     * Originally `NOT NULL`; 20250621140000 ran
     * `ALTER TABLE live_transfers ALTER COLUMN attempted_user_id DROP NOT
     * NULL` (the ON DELETE CASCADE FK itself was untouched — it's still
     * CASCADE, just now on a nullable column).
     */
    attemptedUserId: uuid("attempted_user_id").references(() => users.id, {
      onDelete: "cascade",
    }),
    /** 20250621140000 */
    channel: liveTransferChannelEnum("channel").notNull().default("voice"),
    outcome: liveTransferOutcomeEnum("outcome").notNull(),
    /**
     * The AI's own account of why it escalated, from the `transfer_to_human`
     * tool call. Nullable: every row written before this column existed has
     * none, and a transfer logged for a failure path (no on-call agent) may
     * not carry one either.
     */
    reason: text("reason"),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    // Index names were never renamed when the table was renamed from
    // call_transfers -> live_transfers (`ALTER TABLE RENAME` doesn't
    // rename dependent indexes) — these are the real, current index names.
    index("call_transfers_tenant_idx").on(t.tenantId),
    index("call_transfers_conversation_idx").on(t.conversationId),
  ],
);

// ---------------------------------------------------------------------------
// Outbound batches (bulk-send queue, reside "Notices" integration)
// ---------------------------------------------------------------------------

export const outboundBatches = pgTable("outbound_batches", {
  id: uuid("id").primaryKey().defaultRandom(),
  tenantId: uuid("tenant_id")
    .notNull()
    .references(() => tenants.id, { onDelete: "cascade" }),
  channel: messageChannelEnum("channel").notNull(),
  subject: text("subject"),
  status: text("status")
    .notNull()
    .default("pending"),
  totalRecipients: integer("total_recipients").notNull(),
  completedRecipients: integer("completed_recipients").notNull().default(0),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
  completedAt: timestamp("completed_at", { withTimezone: true }),
}, (t) => [
  check(
    "outbound_batches_status_check",
    sql`${t.status} in ('pending', 'processing', 'completed')`,
  ),
]);

export const outboundBatchRecipients = pgTable(
  "outbound_batch_recipients",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    batchId: uuid("batch_id")
      .notNull()
      .references(() => outboundBatches.id, { onDelete: "cascade" }),
    tenantId: uuid("tenant_id")
      .notNull()
      .references(() => tenants.id, { onDelete: "cascade" }),
    channel: messageChannelEnum("channel").notNull(),
    identityContact: jsonb("identity_contact").notNull(),
    body: text("body").notNull(),
    /**
     * 20250701000000: created with CHECK IN ('pending','sent','failed').
     * 20250701002200: constraint dropped and recreated to add 'sending' as
     * an atomic claim state for multi-replica-safe dispatch. Final form only.
     */
    status: text("status").notNull().default("pending"),
    messageId: uuid("message_id").references(() => messages.id, {
      onDelete: "set null",
    }),
    error: text("error"),
    /** 20250701002200 */
    claimedAt: timestamp("claimed_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    check(
      "outbound_batch_recipients_status_check",
      sql`${t.status} in ('pending', 'sending', 'sent', 'failed')`,
    ),
    index("outbound_batch_recipients_pending_idx")
      .on(t.createdAt)
      .where(sql`${t.status} = 'pending'`),
    index("outbound_batch_recipients_batch_idx").on(t.batchId),
    index("outbound_batch_recipients_claimed_idx")
      .on(t.claimedAt)
      .where(sql`${t.status} = 'sending'`),
  ],
);

// ---------------------------------------------------------------------------
// Tags (Admin Inbox, Phase 2)
// ---------------------------------------------------------------------------

export const tags = pgTable(
  "tags",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    tenantId: uuid("tenant_id")
      .notNull()
      .references(() => tenants.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    color: text("color"),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    // Unnamed in the original SQL (`UNIQUE (tenant_id, name)` inline);
    // Postgres auto-names it tags_tenant_id_name_key. Left unnamed here so
    // drizzle-kit generates the same default name.
    unique().on(t.tenantId, t.name),
    index("tags_tenant_idx").on(t.tenantId),
  ],
);

export const conversationTags = pgTable(
  "conversation_tags",
  {
    conversationId: uuid("conversation_id")
      .notNull()
      .references(() => conversations.id, { onDelete: "cascade" }),
    tagId: uuid("tag_id")
      .notNull()
      .references(() => tags.id, { onDelete: "cascade" }),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    primaryKey({ columns: [t.conversationId, t.tagId] }),
    index("conversation_tags_tag_idx").on(t.tagId),
  ],
);

// ---------------------------------------------------------------------------
// Conversation assignees (multi-assignee support, Admin Inbox Phase 2)
// ---------------------------------------------------------------------------

export const conversationAssignees = pgTable(
  "conversation_assignees",
  {
    conversationId: uuid("conversation_id")
      .notNull()
      .references(() => conversations.id, { onDelete: "cascade" }),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    assignedAt: timestamp("assigned_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    assignedBy: uuid("assigned_by").references(() => users.id, {
      onDelete: "set null",
    }),
  },
  (t) => [
    primaryKey({ columns: [t.conversationId, t.userId] }),
    index("conversation_assignees_user_idx").on(t.userId),
  ],
);

// ---------------------------------------------------------------------------
// Conversation participants (multi-participant support, Admin Inbox Phase 2)
// ---------------------------------------------------------------------------

export const conversationParticipants = pgTable(
  "conversation_participants",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    conversationId: uuid("conversation_id")
      .notNull()
      .references(() => conversations.id, { onDelete: "cascade" }),
    identityId: uuid("identity_id").references(() => identities.id, {
      onDelete: "cascade",
    }),
    userId: uuid("user_id").references(() => users.id, {
      onDelete: "cascade",
    }),
    role: text("role").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    check("conversation_participants_role_check", sql`${t.role} in ('external', 'internal')`),
    check(
      "conversation_participants_check",
      sql`(${t.identityId} is not null) <> (${t.userId} is not null)`,
    ),
    uniqueIndex("conversation_participants_identity_unique")
      .on(t.conversationId, t.identityId)
      .where(sql`${t.identityId} is not null`),
    uniqueIndex("conversation_participants_user_unique")
      .on(t.conversationId, t.userId)
      .where(sql`${t.userId} is not null`),
    index("conversation_participants_conversation_idx").on(t.conversationId),
  ],
);

// ---------------------------------------------------------------------------
// Conversation splits (Admin Inbox, Phase 8)
// ---------------------------------------------------------------------------

export const conversationSplits = pgTable(
  "conversation_splits",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    tenantId: uuid("tenant_id")
      .notNull()
      .references(() => tenants.id, { onDelete: "cascade" }),
    sourceConversationId: uuid("source_conversation_id")
      .notNull()
      .references(() => conversations.id, { onDelete: "cascade" }),
    targetConversationId: uuid("target_conversation_id")
      .notNull()
      .references(() => conversations.id, { onDelete: "cascade" }),
    splitMessageId: uuid("split_message_id").references(() => messages.id, {
      onDelete: "set null",
    }),
    triggerType: text("trigger_type").notNull(),
    triggeredByUserId: uuid("triggered_by_user_id").references(
      () => users.id,
      { onDelete: "set null" },
    ),
    reasoning: text("reasoning"),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    check(
      "conversation_splits_trigger_type_check",
      sql`${t.triggerType} in ('admin', 'ai')`,
    ),
    index("conversation_splits_source_idx").on(t.sourceConversationId),
    index("conversation_splits_target_idx").on(t.targetConversationId),
  ],
);

// ---------------------------------------------------------------------------
// Conversation read states (per-user read tracking, reside dashboard)
// ---------------------------------------------------------------------------

export const conversationReadStates = pgTable(
  "conversation_read_states",
  {
    conversationId: uuid("conversation_id")
      .notNull()
      .references(() => conversations.id, { onDelete: "cascade" }),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    lastReadAt: timestamp("last_read_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    lastReadMessageId: uuid("last_read_message_id").references(
      () => messages.id,
      { onDelete: "set null" },
    ),
  },
  (t) => [
    primaryKey({ columns: [t.conversationId, t.userId] }),
    index("conversation_read_states_user_idx").on(t.userId),
  ],
);

// ---------------------------------------------------------------------------
// Conversation personal tags (per-admin "relevant to me" marker)
// ---------------------------------------------------------------------------

export const conversationPersonalTags = pgTable(
  "conversation_personal_tags",
  {
    conversationId: uuid("conversation_id")
      .notNull()
      .references(() => conversations.id, { onDelete: "cascade" }),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    primaryKey({ columns: [t.conversationId, t.userId] }),
    index("conversation_personal_tags_user_idx").on(t.userId),
  ],
);

// ---------------------------------------------------------------------------
// RAG: documents + chunks (Phase 10)
// ---------------------------------------------------------------------------

export const documents = pgTable(
  "documents",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    tenantId: uuid("tenant_id")
      .notNull()
      .references(() => tenants.id, { onDelete: "cascade" }),
    filename: text("filename").notNull(),
    contentText: text("content_text").notNull(),
    extractor: text("extractor").notNull(),
    pageCount: integer("page_count"),
    status: text("status").notNull().default("pending"),
    failureReason: text("failure_reason"),
    uploadedBy: uuid("uploaded_by").references(() => users.id, {
      onDelete: "set null",
    }),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    check(
      "documents_status_check",
      sql`${t.status} in ('pending', 'processing', 'ready', 'failed')`,
    ),
    index("documents_tenant_idx").on(t.tenantId),
  ],
);

/**
 * tenant_id is denormalized from documents (always derived server-side from
 * the parent document at insert time, never accepted as pass-through input)
 * so retrieval queries can filter by it directly without a join. The
 * document_chunks_tenant_check trigger (packages/database/sql/99-functions-and-triggers.sql)
 * is what actually guarantees the two never drift apart, and it is the only
 * tenant guard here that application code cannot skip. The RLS that used to
 * sit alongside it was decorative for backend code paths — the service role
 * bypassed it entirely — and is gone; see notes.md §3.
 *
 * `embedding` deliberately has NO HNSW/IVFFlat index. HNSW is approximate,
 * and `WHERE tenant_id = X ORDER BY embedding <=> $1 LIMIT k` can find the
 * global top-k across all tenants first and post-filter, silently
 * under-returning results for a small tenant once a larger tenant has
 * loaded many chunks — a completeness bug worse than a typical cross-tenant
 * leak (another tenant's text quietly woven into a real reply). At expected
 * v1 volumes (dozens-to-low-hundreds of chunks/tenant) an exact brute-force
 * scan (see match_document_chunks in the companion SQL) is correct by
 * construction. Do not add a vector index here without a dedicated
 * cross-tenant completeness test alongside it (20250701001500).
 *
 * The unqualified `vector(1536)` type name resolves because the bootstrap SQL
 * installs the extension into `public`, which is on the default search_path
 * for every role — including whichever one drizzle-kit connects as. Installing
 * it into a separate `extensions` schema instead would break migration-apply
 * here unless that schema were added to the migration role's search_path too.
 * See notes.md §5.
 */
export const documentChunks = pgTable(
  "document_chunks",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    documentId: uuid("document_id")
      .notNull()
      .references(() => documents.id, { onDelete: "cascade" }),
    tenantId: uuid("tenant_id")
      .notNull()
      .references(() => tenants.id, { onDelete: "cascade" }),
    chunkIndex: integer("chunk_index").notNull(),
    heading: text("heading"),
    content: text("content").notNull(),
    embedding: vector("embedding", { dimensions: 1536 }),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    index("document_chunks_tenant_idx").on(t.tenantId),
    index("document_chunks_document_idx").on(t.documentId),
    // Deliberately no vector index (hnsw/ivfflat) — see table comment above.
  ],
);
