-- Bootstrap for the shared PlanetScale cluster. Run ONCE, as an admin role,
-- before any drizzle-kit migration. Not generated by drizzle-kit: it creates
-- the schema and role that every later migration assumes already exist.
--
-- Two products share this cluster. comm-canoe lives in `comm_canoe`, reside
-- gets `reside` alongside it. They are loosely coupled - the join key is
-- reside's client uid, and there is deliberately no cross-schema foreign key -
-- so each product's schema is a private world that the other reads only where
-- explicitly granted.
--
-- That last part is the isolation mechanism, and it is doing real work here.
-- comm-canoe's tenant isolation is entirely application-layer: every
-- `WHERE tenant_id = $1` in a service method is the security boundary, and
-- there is no RLS backstop behind it. Schema grants mean a query bug in one
-- product cannot reach the other product's tables at all - enforced by the
-- engine rather than by remembering.

CREATE SCHEMA IF NOT EXISTS comm_canoe;

-- pgvector for document_chunks.embedding. Installed into its own schema so the
-- `vector` type is not owned by, and cannot be dropped with, either product.
CREATE SCHEMA IF NOT EXISTS extensions;
CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA extensions;

-- Every role has to resolve `vector` unqualified, not just the app role.
-- Drizzle emits `embedding vector(1536)` with no schema on it, so whichever
-- role runs `drizzle-kit migrate` needs `extensions` on its search_path too -
-- and that is a PlanetScale-managed admin role we do not name here. Setting it
-- at the database level covers every role at once; the app role's own narrower
-- setting below still wins for the app.
--
-- If the deploying role lacks ALTER DATABASE, the fallback is to schema-qualify
-- the column type in the Drizzle schema instead. Without one of the two,
-- CREATE TABLE fails at migrate time with an unresolved type.
DO $$
BEGIN
  EXECUTE format(
    'ALTER DATABASE %I SET search_path = "$user", public, extensions',
    current_database()
  );
END
$$;

-- The role the app connects as. It owns nothing: migrations run as the admin
-- role, so a compromised app credential cannot DROP or ALTER a table.
-- Password is set out of band - never commit one here.
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'comm_canoe_app') THEN
    CREATE ROLE comm_canoe_app LOGIN;
  END IF;
END
$$;

GRANT USAGE ON SCHEMA comm_canoe TO comm_canoe_app;
GRANT USAGE ON SCHEMA extensions TO comm_canoe_app;

GRANT SELECT, INSERT, UPDATE, DELETE
  ON ALL TABLES IN SCHEMA comm_canoe TO comm_canoe_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA comm_canoe TO comm_canoe_app;

-- Tables created by future migrations need the same grants, and DEFAULT
-- PRIVILEGES is what makes that automatic. Without this, every migration that
-- adds a table silently produces one the app cannot read, and the failure
-- surfaces at runtime rather than at migration time.
ALTER DEFAULT PRIVILEGES IN SCHEMA comm_canoe
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO comm_canoe_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA comm_canoe
  GRANT USAGE, SELECT ON SEQUENCES TO comm_canoe_app;

-- Resolve unqualified names to this product's schema only. `public` is
-- deliberately absent: better-auth's tables live there, and its own migrator
-- connects as its own role. Anything this app needs, it gets by explicit grant.
ALTER ROLE comm_canoe_app SET search_path = comm_canoe, extensions;

-- Reside's schema is created by its own bootstrap when that migration starts.
-- No grant is issued in either direction here. If a cross-product read is ever
-- needed - a combined admin view, a report - it should be one explicit GRANT on
-- one named table, reviewed on its own, rather than a standing permission.
