-- Let a sweep tell an abandoned worker claim from a fresh one.
--
-- outbound_batch_recipients has had claimed_at since 20250701002200, and
-- reclaimStuckOutboundBatchRecipients to go with it. The three message/document
-- workers claim the same way and have no equivalent: if the bridge dies between
-- the claim and the terminal write - a deploy, an OOM, a Railway restart
-- mid-tick - the row sits in its claim state forever, because every
-- listPending* query selects only 'pending'. One message has sat at
-- topic_check_status = 'processing' since 2026-08-11 for exactly that reason.
--
-- `documents` needs no column: every write that moves `status` already stamps
-- updated_at, so on a row held at 'processing' updated_at IS the claim time.
--
-- Generated by drizzle-kit against meta/0009_snapshot.json, with the backfill
-- below added by hand. 0007_long_punisher repaired the snapshot chain that
-- 0006 had broken, so this diff proposed only the four statements here -
-- nothing stale, and the chain stays correct for whoever generates next.
--
-- Plain CREATE INDEX, not CONCURRENTLY: drizzle-orm's migrator wraps every
-- migration file in a single transaction, which CONCURRENTLY cannot join. The
-- table is 77 pages, so the ACCESS EXCLUSIVE lock is single-digit
-- milliseconds and there is nothing to buy here anyway.

ALTER TABLE "messages" ADD COLUMN "claimed_at" timestamp with time zone;--> statement-breakpoint
-- Backfill, hand-added: without it the sweeps cannot see what is ALREADY
-- stranded. Those rows keep claimed_at IS NULL, `claimed_at < cutoff` does not
-- match NULL, and the one row this whole change exists for sits there
-- untouched - a migration that looks applied and fixes nothing.
--
-- created_at is a lower bound on the real claim time, never an upper one, so a
-- backfilled row looks older than it is and is swept on the first tick. That is
-- the right direction to be wrong in: every row in a claim state right now got
-- there under code that had no way out of it.
UPDATE "messages"
SET "claimed_at" = "created_at"
WHERE "topic_check_status" = 'processing'
   OR "transcription_status" = 'transcribing';--> statement-breakpoint
CREATE INDEX "documents_processing_claimed_idx" ON "documents" USING btree ("updated_at") WHERE "documents"."status" = 'processing';--> statement-breakpoint
CREATE INDEX "messages_topic_check_claimed_idx" ON "messages" USING btree ("claimed_at") WHERE "messages"."topic_check_status" = 'processing';--> statement-breakpoint
CREATE INDEX "messages_transcription_claimed_idx" ON "messages" USING btree ("claimed_at") WHERE "messages"."transcription_status" = 'transcribing';
