-- Cluster bootstrap. Run ONCE as the default `postgres` role, before any
-- drizzle-kit migration. Not generated by drizzle-kit: it creates the database
-- and role that every later migration assumes already exist.
--
-- Two products share one PlanetScale cluster, each in its own logical
-- database: comm_canoe here, reside alongside it. This is PlanetScale's own
-- pattern for multiple apps on a cluster, and it is the stronger of the two
-- options considered - a role without CONNECT cannot reach the other product's
-- data at all, rather than merely lacking a GRANT on its tables.
--
-- That matters here specifically. comm-canoe's tenant isolation is entirely
-- application-layer: the Supabase RLS policies read auth.uid(), which this app
-- stopped supplying when it adopted Better Auth, and the connection uses a
-- superuser-ish role that bypasses RLS regardless. Every `WHERE tenant_id = $1`
-- in a service method IS the boundary. Database-level isolation means a bug in
-- that layer stays inside one product.
--
-- What this costs: a cross-product join is now impossible, not just
-- ungranted - Postgres cannot join across logical databases without FDW. That
-- is the accepted price of coupling the two products only through reside's
-- client uid.
--
-- The default PlanetScale `postgres` role is NOSUPERUSER but carries CREATEDB,
-- CREATEROLE and BYPASSRLS, which is enough for everything below.

-- ── Databases ────────────────────────────────────────────────────────────
-- Run these two while connected to the cluster's initial database. CREATE
-- DATABASE cannot run inside a transaction block, so execute them one at a
-- time rather than pasting this whole file into a single psql session.

CREATE DATABASE comm_canoe;

-- Nothing in this file creates reside's database; it arrives with reside's own
-- migration. Listed here only so the intended shape of the cluster is legible
-- from either side.
-- CREATE DATABASE reside;

-- Neither product's data should be reachable by default. PUBLIC is granted
-- CONNECT on every new database unless revoked, which would quietly undo the
-- isolation this whole file exists to establish.
REVOKE CONNECT ON DATABASE comm_canoe FROM PUBLIC;

-- ── Role ─────────────────────────────────────────────────────────────────
-- Owns nothing: migrations run as the default role, so a leaked application
-- credential cannot DROP or ALTER a table. Create it with a password out of
-- band (`pscale role create`, or CREATE ROLE ... LOGIN PASSWORD) and never
-- commit one here.

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'comm_canoe_app') THEN
    CREATE ROLE comm_canoe_app LOGIN;
  END IF;
END
$$;

GRANT CONNECT ON DATABASE comm_canoe TO comm_canoe_app;

-- ── Remaining statements run while connected TO comm_canoe ───────────────
-- \c comm_canoe

-- pgvector for document_chunks.embedding. Installed into `public`, which is
-- already on the default search_path, so Drizzle's unqualified
-- `embedding vector(1536)` resolves for every role without further setup.
-- (Enable the extension for the cluster in the PlanetScale dashboard first if
-- CREATE EXTENSION reports it is not available.)
CREATE EXTENSION IF NOT EXISTS vector;

GRANT USAGE ON SCHEMA public TO comm_canoe_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO comm_canoe_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO comm_canoe_app;

-- Tables created by future migrations need the same grants, and DEFAULT
-- PRIVILEGES is what makes that automatic. Without it, every migration that
-- adds a table produces one the app cannot read, and the failure surfaces at
-- runtime rather than at migration time.
--
-- FOR ROLE postgres is load-bearing, not decoration. Default privileges attach
-- to the role that creates the object, and `pscale sql` connects as a
-- short-lived pscale_api_* role that will not exist next time. Omitting FOR
-- ROLE would bind these defaults to that throwaway identity and silently do
-- nothing for the migrations that matter. `postgres` is the durable role whose
-- credentials drizzle-kit will run under.
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO comm_canoe_app;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
  GRANT USAGE, SELECT ON SEQUENCES TO comm_canoe_app;

-- Better Auth's tables (user, session, account, verification) are created in
-- this same database by `better-auth migrate`, using DATABASE_URL. They are
-- excluded from drizzle-kit's diff via tablesFilter in drizzle.config.ts so it
-- never proposes dropping tables it does not own. The grants above cover them
-- as well, which is what the app needs to read its own sessions.
